spring.application.name=Plania

spring.datasource.url=jdbc:postgresql://localhost:5432/plania_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

app.jwt.secret=Y2hhbmdlLXRoaXMtc2VjcmV0LWluLXByb2R1Y3Rpb24tcGxhbmlhLWp3dC1zaWduYXR1cmU=
app.jwt.expiration-ms=86400000
